using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class BOLETINSCRIPT : MonoBehaviour
{
    public Text BOLETIN;

    public Text AN첿ISIS;
    public Text FILOSOF페;
    public Text MULTIPLATAFORMAS;
    public Text PROGRAMACI흁;
    public Text SOCIOLOG페;
    public Text ARTE;
    public Text NARRATIVA;
    public Text GESTION;
    public Text NEGOCIOS;
    public Text MATEM쳆ICA;





    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (PlayerPrefs.GetInt("Lang") == 1)
        {
            AN첿ISIS.text = "AN첿ISIS Y DISE헲 DE APLICACIONES";
            FILOSOF페.text = "FILOSOF페";
            MULTIPLATAFORMAS.text = "MULTIPLATAFORMAS";
            PROGRAMACI흁.text = "PROGRAMACI흁";
            SOCIOLOG페.text = "SOCIOLOG페";
            ARTE.text = "ARTE";
            NARRATIVA.text = "NARRATIVA DE VIDEOJUEGOS";
            GESTION.text = "GESTION DE PROYECTOS";
            NEGOCIOS.text = "NEGOCIOS DIGITALES";
            MATEM쳆ICA.text = "MATEM쳆ICA";

            BOLETIN.text="BOLETIN";
        }
        else
        {
            AN첿ISIS.text = "ANALYSIS AND DESIGN OF APPLICATIONS";
            FILOSOF페.text = "PHILOSOPHY";
            MULTIPLATAFORMAS.text = "MULTIPLATFORMS";
            PROGRAMACI흁.text = "PROGRAMMING";
            SOCIOLOG페.text = "SOCIOLOGY";
            ARTE.text = "ART";
            NARRATIVA.text = "VIDEO GAME NARRATIVE";
            GESTION.text = "PROJECT MANAGEMENT";
            NEGOCIOS.text = "DIGITAL BUSINESS";
            MATEM쳆ICA.text = "MATHEMATICS";

            BOLETIN.text = "BOLETIN";
        }
    }
}
